# Pre-Processing and Training Data Development

#### -  Create dummy or indicator features for categorical variables

#### - Standardize the magnitude of numeric features using a scaler

#### - Split your data into testing and training datasets

In [124]:
# Import relevant libraries and packages.
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import matplotlib as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import warnings # For handling error messages.

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

In [175]:
#Loading and previewing the dataframe
file = 'final_df.csv'
final_df = pd.read_csv(file, index_col=[0,1])
final_df.head(100)

int_perc  electricity_consumed  population       GDP continent  \
Country Date                                                                    
AFG     1990   0.000000              1.021140    12412.30   33.5173      Asia   
        1991   0.000000              1.044770    13299.00   30.4497      Asia   
        1992   0.000000              0.768050    14485.50   30.0136      Asia   
        1993   0.000000              0.729610    15816.60   24.2715      Asia   
        1994   0.000000              0.750170    17075.70   18.6874      Asia   
        1995   0.000000              0.685440    18110.70   24.3930      Asia   
        1996   0.000000              0.620570    18853.40   25.2627      Asia   
        1997   0.000000              0.564070    19357.10   23.9564      Asia   
        1998   0.000000              0.527800    19737.80   22.8357      Asia   
        1999   0.000000              0.523150    20170.80   21.7440      Asia   
        2000   0.000000              0.534310    20780.00   20.5799      Asia   
        2001   0.004723              0.650560    21607.00   19.4201      Asia   
        2002   0.004561              0.738910    22600.80   28.8519      Asia   
        2003   0.087891              0.973270    23680.90   33.4125      Asia   
        2004   0.105809              0.931420    24726.70   34.3682      Asia   
        2005   1.224148              0.973620    25654.30   36.9487      Asia   
        2006   2.107124              1.210410    26433.10   40.1128      Asia   
        2007   1.900000              1.488780    27100.50   49.1955      Asia   
        2008   1.840000              1.429049    27722.30   48.6518      Asia   
        2009   3.550000              2.027433    28394.80   53.9395      Asia   
        2010   4.000000              2.442759    29185.50   56.7712      Asia   
        2011   5.000000              3.033989    30117.40   60.6103      Asia   
        2012   5.454545              3.919160    31161.40   66.4914      Asia   
        2013   5.900000              4.640790    32269.60   70.9136      Asia   
        2014   6.390000              4.783220    33370.80   73.0931      Asia   
ALB     1990   0.000000              1.659000     3286.07   15.5809    Europe   
        1991   0.000000              1.715000     3280.40   11.2179    Europe   
        1992   0.000000              1.443000     3245.89   10.4103    Europe   
        1993   0.000000              1.727000     3195.20   11.4097    Europe   
        1994   0.000000              2.017000     3146.52   12.3567    Europe   
        1995   0.011169              2.152000     3112.92   14.0002    Europe   
        1996   0.032197              2.790000     3098.70   15.2744    Europe   
        1997   0.048594              2.084000     3099.75   13.6190    Europe   
        1998   0.065027              2.200000     3110.70   14.8459    Europe   
        1999   0.081437              3.482000     3122.70   16.8503    Europe   
        2000   0.114097              3.758360     3129.25   17.9666    Europe   
        2001   0.325798              3.548780     3129.70   19.3931    Europe   
        2002   0.390081              4.545560     3126.18   20.2137    Europe   
        2003   0.971900              4.110580     3118.02   21.3740    Europe   
        2004   2.420388              3.777600     3104.89   22.5866    Europe   
        2005   6.043891              3.738800     3086.81   23.8874    Europe   
        2006   9.609991              2.991420     3063.02   25.1848    Europe   
        2007  15.036115              3.693680     3033.99   26.6720    Europe   
        2008  23.860000              4.053000     3002.68   28.6821    Europe   
        2009  41.200000              4.302000     2973.04   29.6441    Europe   
        2010  45.000000              4.424770     2948.03   30.7430    Europe   
        2011  49.000000              5.141940     2928.60   31.5255    Europe   
        2012  54.655959              4.322650 

## Creating dummy variables for categorical feature, 'continent'

In [176]:
#Manipulating the dataframe to make it easier to work with, is this necessary?
df = final_df.reset_index()
df.set_index('Country', inplace = True)
df

Date  int_perc  electricity_consumed  population      GDP continent  \
Country                                                                        
AFG      1990      0.00               1.02114     12412.3  33.5173      Asia   
AFG      1991      0.00               1.04477     13299.0  30.4497      Asia   
AFG      1992      0.00               0.76805     14485.5  30.0136      Asia   
AFG      1993      0.00               0.72961     15816.6  24.2715      Asia   
AFG      1994      0.00               0.75017     17075.7  18.6874      Asia   
...       ...       ...                   ...         ...      ...       ...   
ZWE      2010     11.50               7.47868     12697.7  26.1448    Africa   
ZWE      2011     15.70               7.91654     12894.3  29.8557    Africa   
ZWE      2012     17.09               7.71048     13115.2  34.8313    Africa   
ZWE      2013     18.50               8.07970     13350.4  35.5243    Africa   
ZWE      2014     19.89               7.96012     13586.7  36.3687    Africa   

        country_name  
Country               
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
...              ...  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  

[4249 rows x 7 columns]

In [180]:
#Checking out the value counts for all the different continents in the dataset. 
df['continent'].value_counts()

Africa           1299
Europe            958
Asia              892
North America     575
South America     300
Oceania           225
Name: continent, dtype: int64

In [181]:
#One-hot encoding to convert 'continents' catagorical data to numerical
df = pd.get_dummies(df, columns = ['continent'])

In [182]:
df

Date  int_perc  electricity_consumed  population      GDP  \
Country                                                              
AFG      1990      0.00               1.02114     12412.3  33.5173   
AFG      1991      0.00               1.04477     13299.0  30.4497   
AFG      1992      0.00               0.76805     14485.5  30.0136   
AFG      1993      0.00               0.72961     15816.6  24.2715   
AFG      1994      0.00               0.75017     17075.7  18.6874   
...       ...       ...                   ...         ...      ...   
ZWE      2010     11.50               7.47868     12697.7  26.1448   
ZWE      2011     15.70               7.91654     12894.3  29.8557   
ZWE      2012     17.09               7.71048     13115.2  34.8313   
ZWE      2013     18.50               8.07970     13350.4  35.5243   
ZWE      2014     19.89               7.96012     13586.7  36.3687   

        country_name  continent_Africa  continent_Asia  continent_Europe  \
Country                                                                    
AFG      Afghanistan                 0               1                 0   
AFG      Afghanistan                 0               1                 0   
AFG      Afghanistan                 0               1                 0   
AFG      Afghanistan                 0               1                 0   
AFG      Afghanistan                 0               1                 0   
...              ...               ...             ...               ...   
ZWE         Zimbabwe                 1               0                 0   
ZWE         Zimbabwe                 1               0                 0   
ZWE         Zimbabwe                 1               0                 0   
ZWE         Zimbabwe                 1               0                 0   
ZWE         Zimbabwe                 1               0                 0   

         continent_North America  continent_Oceania  continent_South America  
Country                                                                       
AFG                            0                  0                        0  
AFG                            0                  0                        0  
AFG                            0                  0                        0  
AFG                            0                  0                        0  
AFG                            0                  0                        0  
...                          ...                ...                      ...  
ZWE                            0                  0                        0  
ZWE                            0                  0                        0  
ZWE                            0                  0                        0  
ZWE                            0                  0                        0  
ZWE                            0                  0                        0  

[4249 rows x 12 columns]

## Splitting the Data in Train/Test Datasets

In [183]:
#Checking dtypes and location for slicing
df.dtypes

Date                         int64
int_perc                   float64
electricity_consumed       float64
population                 float64
GDP                        float64
country_name                object
continent_Africa             uint8
continent_Asia               uint8
continent_Europe             uint8
continent_North America      uint8
continent_Oceania            uint8
continent_South America      uint8
dtype: object

In [197]:
#Seperating features
X = df.iloc[:, [0,1,3,4,6,7,8,9,10,11]]

#Selecting for label (target feature), 'electricity_consumed'
y = df.iloc[:, [2]]


In [198]:
X.head()

Date  int_perc  population      GDP  continent_Africa  \
Country                                                          
AFG      1990       0.0     12412.3  33.5173                 0   
AFG      1991       0.0     13299.0  30.4497                 0   
AFG      1992       0.0     14485.5  30.0136                 0   
AFG      1993       0.0     15816.6  24.2715                 0   
AFG      1994       0.0     17075.7  18.6874                 0   

         continent_Asia  continent_Europe  continent_North America  \
Country                                                              
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   

         continent_Oceania  continent_South America  
Country                                              
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0

In [199]:
y.head()

electricity_consumed
Country                      
AFG                   1.02114
AFG                   1.04477
AFG                   0.76805
AFG                   0.72961
AFG                   0.75017

In [200]:
#Creating the train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

In [201]:
#Checking the shape of the train/test data
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3186, 10) (3186, 1)
(1063, 10) (1063, 1)


## Scaling the X_train data

In [202]:
#Creating the scaler object
scaler = StandardScaler().fit(X_train)

In [204]:
#Checking the mean of the scaler data
scaler.mean_

array([2.00223917e+03, 1.57046767e+01, 3.44227107e+04, 4.14307626e+02,
       3.03201507e-01, 2.16258632e-01, 2.26930320e-01, 1.30257376e-01,
       5.08474576e-02, 7.25047081e-02])

In [205]:
#Checking the variation of the scaler data
scaler.scale_

array([7.19571591e+00, 2.39343739e+01, 1.31301802e+05, 1.41735584e+03,
       4.59641548e-01, 4.11692647e-01, 4.18847168e-01, 3.36586381e-01,
       2.19686125e-01, 2.59321760e-01])

In [207]:
#Transforming the dataset
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[ 1.63442092, -0.00604472, -0.24674963, ..., -0.38699538,
        -0.23145502, -0.27959361],
       [-0.72809592, -0.6552518 , -0.05078461, ..., -0.38699538,
        -0.23145502, -0.27959361],
       [-1.70089697, -0.65615573, -0.2528647 , ...,  2.58401015,
        -0.23145502, -0.27959361],
       ...,
       [-0.72809592, -0.65433171, -0.19061117, ..., -0.38699538,
        -0.23145502, -0.27959361],
       [-1.56192539, -0.65615573, -0.25942651, ..., -0.38699538,
        -0.23145502, -0.27959361],
       [ 0.24470513, -0.4755956 , -0.12638753, ..., -0.38699538,
        -0.23145502, -0.27959361]])

In [210]:
#Checking the mean of the scaled data
print(X_train_scaled.mean(axis = 0))

[ 1.18379185e-14 -2.78775399e-17 -3.34530478e-17  3.12228446e-17
 -7.02514004e-17 -7.80571116e-17 -1.56114223e-17 -4.46040638e-18
  6.46758925e-17 -8.36326196e-18]


In [196]:
#Checking that the scaled data has a standard deviation of 1
print(X_train_scaled.std(axis = 0))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Scaling the X_test data

In [221]:
#Creating the scaler object
scaler = StandardScaler().fit(X_test)

#Checking the mean of the scaler data
print(scaler.mean_)

[2.00195202e+03 1.55859083e+01 3.95992091e+04 4.32387995e+02
 3.13264346e-01 1.90968956e-01 2.21072437e-01 1.50517404e-01
 5.92662277e-02 6.49106303e-02]


In [222]:
#Checking the variation of the scaler data
print(scaler.scale_)



[7.04083995e+00 2.36161384e+01 1.41385113e+05 1.35219184e+03
 4.63820866e-01 3.93064643e-01 4.14969173e-01 3.57577844e-01
 2.36122303e-01 2.46368099e-01]


In [223]:
#Transforming the dataset
X_test_scaled = scaler.transform(X_test)
print(X_test_scaled)

[[-0.70332838 -0.65707982 -0.20235164 ...  2.3756578  -0.25099801
  -0.26347011]
 [-1.12941391 -0.65996853 -0.11501005 ... -0.42093604 -0.25099801
  -0.26347011]
 [ 1.42709925 -0.41865104 -0.12811751 ... -0.42093604 -0.25099801
  -0.26347011]
 ...
 [-0.9873854  -0.65996853 -0.24778499 ... -0.42093604 -0.25099801
  -0.26347011]
 [ 1.56912776  1.50126541  1.14349586 ... -0.42093604 -0.25099801
   3.79549695]
 [ 1.71115627  1.03378848 -0.27936595 ... -0.42093604  3.98409536
  -0.26347011]]


In [224]:
#Checking the mean of the scaled data
print(X_test_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(X_test_scaled.std(axis = 0))

[ 8.26181394e-15 -6.76786943e-17  3.75992746e-17  4.01058929e-17
 -1.00264732e-17 -4.21947415e-17 -4.51191295e-17  6.35009971e-17
 -3.67637352e-17 -4.34480506e-17]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Scaling the y_train data

In [227]:
#Creating the scaler object
scaler = StandardScaler().fit(y_train)

#Checking the mean of the scaler data
print(scaler.mean_)

[82.6324499]


In [228]:
#Checking the variation of the scaler data
print(scaler.scale_)

[356.94317509]


In [229]:
#Transforming the dataset
y_train_scaled = scaler.transform(y_train)
print(y_train_scaled)

[[-0.23080438]
 [-0.19756212]
 [-0.22291349]
 ...
 [-0.21107127]
 [-0.22807118]
 [-0.1664143 ]]


In [230]:
#Checking the mean of the scaled data
print(y_train_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(y_train_scaled.std(axis = 0))

[-2.28595827e-17]
[1.]


## Scaling the y_test data

In [231]:
#Creating the scaler object
scaler = StandardScaler().fit(y_test)

#Checking the mean of the scaler data
print(scaler.mean_)

[85.5924136]


In [232]:
#Checking the variation of the scaler data
print(scaler.scale_)

[332.61645488]


In [233]:
#Transforming the dataset
y_test_scaled = scaler.transform(y_test)
print(y_test_scaled)

[[-0.22502018]
 [-0.25345533]
 [-0.24260319]
 ...
 [-0.23329698]
 [ 1.26006486]
 [-0.25719366]]


In [234]:
#Checking the mean of the scaled data
print(y_test_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(y_test_scaled.std(axis = 0))

[6.68431548e-18]
[1.]


## Questions:

- Do I need to simplify the index in the beginning of the notebook like it did, or can this be done maintaining a multi-index format?

- Should I be approaching the train/test split differently considering that this is a time series problem? 

- What is the best way to save the X_train, X_test, y_train, y_test datasets to open in the next notebook for the project? As seperate csv files? 