# Pre-Processing and Training Data Development

#### -  Create dummy or indicator features for categorical variables

#### - Standardize the magnitude of numeric features using a scaler

#### - Split your data into testing and training datasets

In [77]:
# Import relevant libraries and packages.
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import matplotlib as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit

import warnings # For handling error messages.

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

In [78]:
#Loading and previewing the dataframe
file = 'final_df.csv'
final_df = pd.read_csv(file, index_col=[0,1])
final_df.head(100)

int_perc  electricity_consumed  population       GDP continent  \
Country Date                                                                    
AFG     1990   0.000000              1.021140    12412.30   33.5173      Asia   
        1991   0.000000              1.044770    13299.00   30.4497      Asia   
        1992   0.000000              0.768050    14485.50   30.0136      Asia   
        1993   0.000000              0.729610    15816.60   24.2715      Asia   
        1994   0.000000              0.750170    17075.70   18.6874      Asia   
        1995   0.000000              0.685440    18110.70   24.3930      Asia   
        1996   0.000000              0.620570    18853.40   25.2627      Asia   
        1997   0.000000              0.564070    19357.10   23.9564      Asia   
        1998   0.000000              0.527800    19737.80   22.8357      Asia   
        1999   0.000000              0.523150    20170.80   21.7440      Asia   
        2000   0.000000              0.534310    20780.00   20.5799      Asia   
        2001   0.004723              0.650560    21607.00   19.4201      Asia   
        2002   0.004561              0.738910    22600.80   28.8519      Asia   
        2003   0.087891              0.973270    23680.90   33.4125      Asia   
        2004   0.105809              0.931420    24726.70   34.3682      Asia   
        2005   1.224148              0.973620    25654.30   36.9487      Asia   
        2006   2.107124              1.210410    26433.10   40.1128      Asia   
        2007   1.900000              1.488780    27100.50   49.1955      Asia   
        2008   1.840000              1.429049    27722.30   48.6518      Asia   
        2009   3.550000              2.027433    28394.80   53.9395      Asia   
        2010   4.000000              2.442759    29185.50   56.7712      Asia   
        2011   5.000000              3.033989    30117.40   60.6103      Asia   
        2012   5.454545              3.919160    31161.40   66.4914      Asia   
        2013   5.900000              4.640790    32269.60   70.9136      Asia   
        2014   6.390000              4.783220    33370.80   73.0931      Asia   
ALB     1990   0.000000              1.659000     3286.07   15.5809    Europe   
        1991   0.000000              1.715000     3280.40   11.2179    Europe   
        1992   0.000000              1.443000     3245.89   10.4103    Europe   
        1993   0.000000              1.727000     3195.20   11.4097    Europe   
        1994   0.000000              2.017000     3146.52   12.3567    Europe   
        1995   0.011169              2.152000     3112.92   14.0002    Europe   
        1996   0.032197              2.790000     3098.70   15.2744    Europe   
        1997   0.048594              2.084000     3099.75   13.6190    Europe   
        1998   0.065027              2.200000     3110.70   14.8459    Europe   
        1999   0.081437              3.482000     3122.70   16.8503    Europe   
        2000   0.114097              3.758360     3129.25   17.9666    Europe   
        2001   0.325798              3.548780     3129.70   19.3931    Europe   
        2002   0.390081              4.545560     3126.18   20.2137    Europe   
        2003   0.971900              4.110580     3118.02   21.3740    Europe   
        2004   2.420388              3.777600     3104.89   22.5866    Europe   
        2005   6.043891              3.738800     3086.81   23.8874    Europe   
        2006   9.609991              2.991420     3063.02   25.1848    Europe   
        2007  15.036115              3.693680     3033.99   26.6720    Europe   
        2008  23.860000              4.053000     3002.68   28.6821    Europe   
        2009  41.200000              4.302000     2973.04   29.6441    Europe   
        2010  45.000000              4.424770     2948.03   30.7430    Europe   
        2011  49.000000              5.141940     2928.60   31.5255    Europe   
        2012  54.655959              4.322650 

## Creating dummy variables for categorical feature, 'continent'

In [5]:
#Manipulating the dataframe to make it easier to work with, is this necessary?
df = final_df.reset_index()
df.set_index('Country', inplace = True)
df

Date  int_perc  electricity_consumed  population      GDP continent  \
Country                                                                        
AFG      1990      0.00               1.02114     12412.3  33.5173      Asia   
AFG      1991      0.00               1.04477     13299.0  30.4497      Asia   
AFG      1992      0.00               0.76805     14485.5  30.0136      Asia   
AFG      1993      0.00               0.72961     15816.6  24.2715      Asia   
AFG      1994      0.00               0.75017     17075.7  18.6874      Asia   
...       ...       ...                   ...         ...      ...       ...   
ZWE      2010     11.50               7.47868     12697.7  26.1448    Africa   
ZWE      2011     15.70               7.91654     12894.3  29.8557    Africa   
ZWE      2012     17.09               7.71048     13115.2  34.8313    Africa   
ZWE      2013     18.50               8.07970     13350.4  35.5243    Africa   
ZWE      2014     19.89               7.96012     13586.7  36.3687    Africa   

        country_name  
Country               
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
AFG      Afghanistan  
...              ...  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  
ZWE         Zimbabwe  

[4249 rows x 7 columns]

In [76]:
df.loc['USA']

KeyError: 'USA'

In [7]:
#One-hot encoding to convert 'continents' catagorical data to numerical
df = pd.get_dummies(df, columns = ['continent'])

In [61]:
df = df.reset_index().set_index('Date')
df

Country  int_perc  electricity_consumed  population      GDP  \
Date                                                                
1990     AFG      0.00               1.02114     12412.3  33.5173   
1991     AFG      0.00               1.04477     13299.0  30.4497   
1992     AFG      0.00               0.76805     14485.5  30.0136   
1993     AFG      0.00               0.72961     15816.6  24.2715   
1994     AFG      0.00               0.75017     17075.7  18.6874   
...      ...       ...                   ...         ...      ...   
2010     ZWE     11.50               7.47868     12697.7  26.1448   
2011     ZWE     15.70               7.91654     12894.3  29.8557   
2012     ZWE     17.09               7.71048     13115.2  34.8313   
2013     ZWE     18.50               8.07970     13350.4  35.5243   
2014     ZWE     19.89               7.96012     13586.7  36.3687   

     country_name  continent_Africa  continent_Asia  continent_Europe  \
Date                                                                    
1990  Afghanistan                 0               1                 0   
1991  Afghanistan                 0               1                 0   
1992  Afghanistan                 0               1                 0   
1993  Afghanistan                 0               1                 0   
1994  Afghanistan                 0               1                 0   
...           ...               ...             ...               ...   
2010     Zimbabwe                 1               0                 0   
2011     Zimbabwe                 1               0                 0   
2012     Zimbabwe                 1               0                 0   
2013     Zimbabwe                 1               0                 0   
2014     Zimbabwe                 1               0                 0   

      continent_North America  continent_Oceania  continent_South America  
Date                                                                       
1990                        0                  0                        0  
1991                        0                  0                        0  
1992                        0                  0                        0  
1993                        0                  0                        0  
1994                        0                  0                        0  
...                       ...                ...                      ...  
2010                        0                  0                        0  
2011                        0                  0                        0  
2012                        0                  0                        0  
2013                        0                  0                        0  
2014                        0                  0                        0  

[4249 rows x 12 columns]

In [87]:
final_df.tail(223)

int_perc  electricity_consumed  population           GDP  \
Country Date                                                              
USA     1990   0.784729           2837.116986  249516.800   9798.600000   
        1991   1.163194           2886.097489  252831.200   9787.970000   
        1992   1.724203           2897.247672  256391.200  10132.740000   
        1993   2.271673           3000.745154  259809.500  10411.670000   
        1994   4.862781           3080.938525  263017.800  10831.180000   
        1995   9.237088           3164.020666  266179.200  11121.900000   
        1996  16.419353           3253.831146  269310.500  11541.470000   
        1997  21.616401           3301.923343  272559.200  12054.740000   
        1998  30.093197           3425.180366  275762.200  12594.970000   
        1999  35.848724           3483.813775  278941.500  13193.660000   
        2000  43.079163           3592.467273  282054.200  13738.200000   
        2001  49.080832           3557.240313  284871.000  13875.380000   
        2002  58.785404           3631.808658  287541.800  14117.040000   
        2003  61.697117           3662.213912  290063.800  14520.950000   
        2004  64.758256           3716.178543  292729.800  15072.580000   
        2005  67.968053           3811.327677  295431.200  15602.130000   
        2006  68.931193           3817.346635  298284.800  16047.550000   
        2007  75.000000           3890.938492  301153.500  16348.630000   
        2008  74.000000           3867.298540  304006.200  16326.300000   
        2009  71.000000           3725.261645  306700.500  15912.140000   
        2010  71.690000           3889.162285  309255.800  16320.090000   
        2011  69.729461           3886.425540  311509.500  16573.210000   
        2012  79.300000           3838.457300  313785.200  16946.000000   
        2013  84.200000           3876.461305  315966.000  17258.190000   
        2014  87.360000           3914.506810  318268.000  17694.100000   
URY     1990   0.000000              5.091000    3109.600     32.054100   
        1991   0.000000              4.107000    3131.660     33.188400   
        1992   0.000000              4.201000    3154.460     35.820800   
        1993   0.000000              4.540000    3177.730     36.772700   
        1994   0.062474              4.733000    3201.150     39.450300   
        1995   0.310129              5.040000    3224.270     38.879200   
        1996   1.847472              5.112000    3247.380     41.047900   
        1997   3.363240              5.591000    3270.160     43.119800   
        1998   6.987069              6.343000    3291.050     45.076800   
        1999   9.972765              6.201000    3308.000     44.203500   
        2000  10.539058              6.474000    3319.730     43.337300   
        2001  11.121438              6.642000    3325.470     41.676700   
        2002  11.419470              6.147000    3326.050     38.460600   
        2003  15.937137              6.033000    3323.660     38.765800   
        2004  17.063098              6.228000    3321.490     40.692900   
        2005  20.088190              6.514000    3321.800     43.744100   
        2006  29.400000              7.251000    3325.400     45.548500   
        2007  34.000000              7.915800    3331.750     48.520800   
        2008  39.300000              8.419320    3340.220     52.010400   
        2009  41.800000              8.718680    3349.680     54.197100   
        2010  46.400000              9.490340    3359.270     58.430200   
        2011  51.404661              9.537480    3368.930     61.446300   
        2012  54.453769              9.967760    3378.980     63.626000   
        2013  57.690000              9.981760    3389.440     66.577200   
        2014  61.460000             10.337840    3400.440     68.730500   
UZB     1992   0.000000             42.796000   21375.100     64.400200   
        1993   0.000000             41.7

In [88]:
final_df.loc['USA']

int_perc  electricity_consumed  population       GDP      continent  \
Date                                                                         
1990   0.784729           2837.116986    249516.8   9798.60  North America   
1991   1.163194           2886.097489    252831.2   9787.97  North America   
1992   1.724203           2897.247672    256391.2  10132.74  North America   
1993   2.271673           3000.745154    259809.5  10411.67  North America   
1994   4.862781           3080.938525    263017.8  10831.18  North America   
1995   9.237088           3164.020666    266179.2  11121.90  North America   
1996  16.419353           3253.831146    269310.5  11541.47  North America   
1997  21.616401           3301.923343    272559.2  12054.74  North America   
1998  30.093197           3425.180366    275762.2  12594.97  North America   
1999  35.848724           3483.813775    278941.5  13193.66  North America   
2000  43.079163           3592.467273    282054.2  13738.20  North America   
2001  49.080832           3557.240313    284871.0  13875.38  North America   
2002  58.785404           3631.808658    287541.8  14117.04  North America   
2003  61.697117           3662.213912    290063.8  14520.95  North America   
2004  64.758256           3716.178543    292729.8  15072.58  North America   
2005  67.968053           3811.327677    295431.2  15602.13  North America   
2006  68.931193           3817.346635    298284.8  16047.55  North America   
2007  75.000000           3890.938492    301153.5  16348.63  North America   
2008  74.000000           3867.298540    304006.2  16326.30  North America   
2009  71.000000           3725.261645    306700.5  15912.14  North America   
2010  71.690000           3889.162285    309255.8  16320.09  North America   
2011  69.729461           3886.425540    311509.5  16573.21  North America   
2012  79.300000           3838.457300    313785.2  16946.00  North America   
2013  84.200000           3876.461305    315966.0  17258.19  North America   
2014  87.360000           3914.506810    318268.0  17694.10  North America   

                  country_name  
Date                            
1990  United States of America  
1991  United States of America  
1992  United States of America  
1993  United States of America  
1994  United States of America  
1995  United States of America  
1996  United States of America  
1997  United States of America  
1998  United States of America  
1999  United States of America  
2000  United States of America  
2001  United States of America  
2002  United States of America  
2003  United States of America  
2004  United States of America  
2005  United States of America  
2006  United States of America  
2007  United States of America  
2008  United States of America  
2009  United States of America  
2010  United States of America  
2011  United States of America  
2012  United States of America  
2013  United States of America  
2014  United States of America

## Splitting the Data in Train/Test Datasets

In [9]:
#Checking dtypes and location for slicing
df.dtypes

Date                         int64
int_perc                   float64
electricity_consumed       float64
population                 float64
GDP                        float64
country_name                object
continent_Africa             uint8
continent_Asia               uint8
continent_Europe             uint8
continent_North America      uint8
continent_Oceania            uint8
continent_South America      uint8
dtype: object

In [49]:
#Seperating features
X = df.iloc[:, [0,1,3,4,6,7,8,9,10,11]].set_index(['Country', 'Date'])

#Selecting for label (target feature), 'electricity_consumed'
y = df.iloc[:, [2]]


KeyError: "None of ['Country'] are in the columns"

In [11]:
X.head()

Date  int_perc  population      GDP  continent_Africa  \
Country                                                          
AFG      1990       0.0     12412.3  33.5173                 0   
AFG      1991       0.0     13299.0  30.4497                 0   
AFG      1992       0.0     14485.5  30.0136                 0   
AFG      1993       0.0     15816.6  24.2715                 0   
AFG      1994       0.0     17075.7  18.6874                 0   

         continent_Asia  continent_Europe  continent_North America  \
Country                                                              
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   
AFG                   1                 0                        0   

         continent_Oceania  continent_South America  
Country                                              
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0  
AFG                      0                        0

In [12]:
y.head()

electricity_consumed
Country                      
AFG                   1.02114
AFG                   1.04477
AFG                   0.76805
AFG                   0.72961
AFG                   0.75017

In [13]:
#Creating the train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25)

In [14]:
#Checking the shape of the train/test data
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3186, 10) (3186, 1)
(1063, 10) (1063, 1)


## Scaling the X_train data

In [15]:
#Creating the scaler object
scaler = StandardScaler().fit(X_train)

In [16]:
#Checking the mean of the scaler data
scaler.mean_

array([2.00214030e+03, 1.56741247e+01, 3.59428859e+04, 4.25742848e+02,
       3.01004394e-01, 2.13119900e-01, 2.24105461e-01, 1.34965474e-01,
       5.17890772e-02, 7.50156937e-02])

In [17]:
#Checking the variation of the scaler data
scaler.scale_

array([7.17055878e+00, 2.38698691e+01, 1.31572705e+05, 1.40700415e+03,
       4.58694614e-01, 4.09511670e-01, 4.16991851e-01, 3.41686691e-01,
       2.21600922e-01, 2.63416665e-01])

In [18]:
#Transforming the dataset
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[ 0.81718857,  3.00570879, -0.14811002, ..., -0.39499775,
        -0.23370425, -0.2847796 ],
       [ 0.25935199, -0.57386105,  8.33006448, ..., -0.39499775,
        -0.23370425, -0.2847796 ],
       [ 0.81718857,  0.42756311, -0.0631367 , ..., -0.39499775,
        -0.23370425,  3.51148742],
       ...,
       [-1.27469861, -0.65664896, -0.24027724, ..., -0.39499775,
        -0.23370425, -0.2847796 ],
       [-0.85632118, -0.60238807,  0.02040875, ..., -0.39499775,
        -0.23370425, -0.2847796 ],
       [ 1.37502515,  2.8653645 ,  0.10761156, ..., -0.39499775,
        -0.23370425, -0.2847796 ]])

In [19]:
#Checking the mean of the scaled data
print(X_train_scaled.mean(axis = 0))

[ 1.00961298e-14 -2.78775399e-17  2.23020319e-17 -1.89567271e-17
  2.89926414e-17  4.46040638e-17 -7.80571116e-18  6.57909941e-17
 -8.92081275e-18 -8.14024164e-17]


In [20]:
#Checking that the scaled data has a standard deviation of 1
print(X_train_scaled.std(axis = 0))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Scaling the X_test data

In [21]:
#Creating the scaler object
scaler = StandardScaler().fit(X_test)

#Checking the mean of the scaler data
print(scaler.mean_)

[2.00224835e+03 1.56774781e+01 3.50429739e+04 3.98114601e+02
 3.19849483e-01 2.00376294e-01 2.29539040e-01 1.36406397e-01
 5.64440263e-02 5.73847601e-02]


In [22]:
#Checking the variation of the scaler data
print(scaler.scale_)



[7.12107591e+00 2.38112301e+01 1.40697533e+05 1.38409671e+03
 4.66418043e-01 4.00281944e-01 4.20536407e-01 3.43219597e-01
 2.30777161e-01 2.32576330e-01]


In [23]:
#Transforming the dataset
X_test_scaled = scaler.transform(X_test)
print(X_test_scaled)

[[-0.73701696 -0.65569403 -0.13956871 ... -0.39743184 -0.24458238
  -0.24673517]
 [-0.73701696 -0.65737172 -0.2044196  ... -0.39743184 -0.24458238
  -0.24673517]
 [ 0.24598057  1.603551   -0.17495455 ... -0.39743184 -0.24458238
  -0.24673517]
 ...
 [-1.15830161 -0.6584069  -0.15502741 ... -0.39743184 -0.24458238
  -0.24673517]
 [ 0.10555235  1.68922486  0.33067372 ... -0.39743184 -0.24458238
  -0.24673517]
 [-0.45616052 -0.6500275  -0.03141188 ... -0.39743184 -0.24458238
  -0.24673517]]


In [24]:
#Checking the mean of the scaled data
print(X_test_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(X_test_scaled.std(axis = 0))

[-1.03573468e-14 -4.34480506e-17 -1.33686310e-17 -3.34215774e-18
 -4.51191295e-17 -3.67637352e-17  0.00000000e+00 -3.84348140e-17
  3.34215774e-18  6.85142337e-17]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Scaling the y_train data

In [25]:
#Creating the scaler object
scaler = StandardScaler().fit(y_train)

#Checking the mean of the scaler data
print(scaler.mean_)

[84.0089052]


In [26]:
#Checking the variation of the scaler data
print(scaler.scale_)

[351.34182252]


In [27]:
#Transforming the dataset
y_train_scaled = scaler.transform(y_train)
print(y_train_scaled)

[[ 0.0826892 ]
 [ 1.10144614]
 [-0.00129579]
 ...
 [-0.23852906]
 [ 0.07767454]
 [ 1.13615843]]


In [28]:
#Checking the mean of the scaled data
print(y_train_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(y_train_scaled.std(axis = 0))

[6.69060956e-18]
[1.]


## Scaling the y_test data

In [29]:
#Creating the scaler object
scaler = StandardScaler().fit(y_test)

#Checking the mean of the scaler data
print(scaler.mean_)

[81.46693232]


In [30]:
#Checking the variation of the scaler data
print(scaler.scale_)

[350.03756339]


In [31]:
#Transforming the dataset
y_test_scaled = scaler.transform(y_test)
print(y_test_scaled)

[[-0.10431718]
 [-0.23193863]
 [ 0.00503954]
 ...
 [-0.22636408]
 [ 1.32150979]
 [-0.17990907]]


In [32]:
#Checking the mean of the scaled data
print(y_test_scaled.mean(axis = 0))

#Checking that the scaled data has a standard deviation of 1
print(y_test_scaled.std(axis = 0))

[3.34215774e-17]
[1.]


## Questions:

- Do I need to simplify the index in the beginning of the notebook like it did, or can this be done maintaining a multi-index format?

- Should I be approaching the train/test split differently considering that this is a time series problem? 

- What is the best way to save the X_train, X_test, y_train, y_test datasets to open in the next notebook for the project? As seperate csv files? 

In [47]:
tscv = TimeSeriesSplit(n_splits=5)

In [48]:
tscv

TimeSeriesSplit(max_train_size=None, n_splits=5)