In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


## #1 Importing the Training/Testing Datasets

In [38]:
X_train_scaled_file = 'X_train_scaled.csv'
X_test_scaled_file = 'X_test_scaled.csv'
y_train_file = 'y_train.csv'
y_test_file = 'y_test.csv'

X_train = pd.read_csv(X_train_scaled_file)
X_test = pd.read_csv(X_test_scaled_file)
y_train = pd.read_csv(y_train_file)
y_test = pd.read_csv(y_test_file)

In [39]:
X_train.drop('Unnamed: 0', axis = 1, inplace = True)
X_train = X_train.to_numpy()
X_train

array([[-0.04065752,  0.73354149,  0.50636585, ..., -0.30373045,
         2.05920773, -0.49214303],
       [ 0.49393646,  1.91845957, -0.13513942, ..., -1.4110529 ,
         0.34864795,  0.72592857],
       [ 0.55224323,  0.45417305, -0.70103366, ...,  1.17709757,
         3.63000018, -1.42983011],
       ...,
       [-0.92752051,  1.03779728, -0.58171413, ..., -0.00971582,
        -0.73473724, -0.4369237 ],
       [ 1.5446067 ,  0.88046308,  0.41923997, ...,  0.78516069,
        -0.45004194,  0.80234474],
       [-1.02890056,  1.00153961,  1.4931661 , ...,  0.19529911,
        -1.21512387, -1.50066819]])

In [40]:
y_train.drop('Unnamed: 0', axis = 1, inplace = True)
y_train = y_train.to_numpy()
y_train

array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [0.],
       [0.]])

In [41]:
X_test.drop('Unnamed: 0', axis = 1, inplace = True)
X_test = X_test.to_numpy()
X_test

array([[ 0.52054247, -1.21420804,  0.68995852, ...,  1.36163155,
        -0.84743376,  1.21524378],
       [ 1.15694553,  2.26259551, -1.12503563, ...,  0.50499985,
         0.10866589,  2.0524329 ],
       [ 0.28294415,  0.62589991, -1.4266366 , ..., -0.92124857,
        -0.82793462, -0.28975052],
       ...,
       [ 0.78521969, -0.34700025, -0.05562609, ..., -0.15015417,
         0.35466531, -1.74709731],
       [ 0.4949676 , -0.36790893, -1.38750794, ..., -0.58763812,
         1.52116374,  0.93949046],
       [ 0.59693533, -0.28715363, -0.07547201, ..., -0.11301154,
         1.25333958,  1.45121498]])

In [42]:
y_test.drop('Unnamed: 0', axis = 1, inplace = True)
y_test = y_test.to_numpy()
y_test

array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rf_model = RandomForestClassifier()

In [51]:
rf_model.fit(X_train, y_train.values.ravel())

AttributeError: 'numpy.ndarray' object has no attribute 'values'